import { Link } from "react-router-dom";

const Supervisor = () => {

    return (
      <>
       

       
    <h1>Reviewing an application as a supervisor</h1>
    <h2>Email notification</h2>
    <h6>You will receive and email stating that have been selected as supervisor to a project. The student name and title of the project will be included.

    Attached to the email there will be a pdf which is the application of the student, generated by the system. In the application some links to other documents will be included (see the section The process/2. Applicant completes the form). 

    You should read the application carefully making sure that:

    The information provided is correct

    The Aim and Objectives of the project are explained in simple (non technical terms)

    The Methodology of the project are explained in simple (non technical terms)

    The Safety concerns of the project are explained in simple (non technical terms)

    All necessary supporting documents are attached, and are properly adapted from the provided templates

    The questions are correct. Keep in mind that if major changes in the questions are required the student should reapply.
 
    At the bottom of the email you will have two options (see fig 1):

    Acknowledge receipt: Selecting this button if you completely agree with the application. This option will directly forward the application for ethics review.

    Comment: Selecting this option will open a browser window where you can add a comment to the student (see fig 2). IMPORTANT: In this window you will again have two options (Acknowledge Receipt or Request More Info). Selecting Acknowledge Receipt, will also forward the application for ethics approval, but send your comments to the student. If you want the student to make changes before the submission you should press the Request More Info link to send the application back to the student.</h6>
    
    <h6>If the application is deemed low risk it is likely that you will be assigned the reviewer. In this case see the page Guide for Reviewers

    When the student receives the approval you will also be notified and sent the approval letter (as a pdf).</h6>
  

      </>
    );
  };
  
  export default Supervisor;