import { Link } from "react-router-dom";

const Reviewer = () => {

    return (
      <>
       

       
    <h1>Reviewing an application as an ethics reviewer</h1>
    <h2>Email notification</h2>
    <h6><p>You will receive and email stating that have been selected as a reviewer to a project. The student name and title of the project will be included.</p>

    <p>Attached to the email there will be a pdf which is the application of the student, generated by the system. In the application some links to other documents will be included (see the section The process/2. Applicant completes the form).</p>

    <p>You should read the application carefully making sure that:</p>

    <p>The information provided is correct</p>

    <p>The Aim and Objectives of the project are explained in simple (non technical terms)</p>

    <p>The Methodology of the project are explained in simple (non technical terms)</p>

    <p>The Safety concerns of the project are explained in simple (non technical terms)</p>

    <p>All necessary supporting documents are attached, and are properly adapted from the provided templates</p>

    <p>At the bottom of the email you will have two options (see fig 1):</p>

    <p>Complete task: Selecting this button if you completely agree with the application. This option will directly approve it and no further steps will be needed from your part.</p>

    <p>Comment: Selecting this option will open a browser window where you can add a comment to the student. IMPORTANT: In this window you will again have two options (Complete task or Request More Info, see fig 2). Selecting Complete task, will also approve the application and send your comments to the applicant. Selecting Request More Info, will send an email to the applicant with your comments, requesting changes to be made. The applicant will have to edit the application and resubmit it. If you want the applicant to make changes before you accept the application, then you should use this option. </p>  </h6>

    
  

      </>
    );
  };
  
  export default Reviewer;